### ISSUE TITLE
Add prediction for NetObject_ModAPI_Sprite

### ISSUE THREAD

**Issue by necropotame** [teeworlds-modapi/teeworlds#2]
Like for NetObject_Flag, the previous position can be used to improve the position prediction of a sprite.

**Comment by killaTW** [comment]
Sprites dont have a  velocity yet,should this also be added? (without prediction is a bit senseless)

**Comment by necropotame** [comment]
Look at RenderPickup(), they just use the previous snapshot to predict the new position. It's not perfect, but it's good enough to make motion smooth. We can think about NetObject_ModAPI_MovingSprite, but I'm not sure if adding velocity is enough.
