### ISSUE TITLE
Add src/mod directory

### ISSUE THREAD

**Issue by necropotame** [teeworlds-modapi/teeworlds#23]
This directory must contains files modified by moders, like src/game/server/gametypes/mod.cpp. In theory, moders must avoid editing other folders. This means that we must provide more virtual functions and classes to allows modification of the game.

**Comment by necropotame** [comment]
This part start to become critical. To provide examples, it's better to have it. We need to discuss a little about how to do it.
First problem, the name of the folder : ./src/mymod, ./src/mod, something else ?
Second problem, what to mod inside ? I think that all ./src/game/server/entities must be moved here since they are always modified. We must also move gametypes here. We must also move the CreateMod() function in the directory. Any other idea ?

**Comment by ghost** [comment]
I don't think we want to provide an api and deny modder to change these files. I think it's better to keep basic structures. I think this api is not about a "plugin" api which should only be used, I think this project is about to provide server modder client features, like special scoreboard (not implemented yet). I wouldn't change much.

**Comment by necropotame** [comment]
Anyways, you can't force someone to don't edit something (look at TW :-p) But it's always better to separate clearly what you did from the original version. In particular is you want to pull some updates from ModAPI or TW.
In the ./src/mod we can guaranty that things will remains stable. Not in the the others part of the code. That's why ModAPI is more or less an API ^^
It's also about learning curve. If you want to start a new mod, you don't have to look at the code of TW. You just have to read some tutorial that explains you how to work in the ./src/mod directory.

**Comment by Henningstone** [comment]
+1, it's always good to keep Spaghetti low. Furthermore, @Schwertspize I think that @necropotame knows what he wants by himself, so you don't have to explain him what he wants for his project :)

**Comment by necropotame** [comment]
Oh it's not _my_ project at all (you have all full access to the repository). I'm always open to discussion and I prefer that something was done after discuss it. Arguments are the best solution to a problem than hierarchy ;-)

b.t.w, you can check the moddir branch if you want. As usual, the commit list is a shame. This time I will fix it :-p.
