### ISSUE TITLE
Add NetObject_ModAPI_Text

### ISSUE THREAD

**Issue by necropotame** [teeworlds-modapi/teeworlds#3]
struct NetObject_ModAPI_Text
{
int m_X;
int m_Y;
char\* m_Text;
}

This NetObject display a text on the world like names (same size and font).

**Comment by abck** [comment]
text relative to the players position or to the map (game layer)?
maybe add state witch says if the text is centerd or on the left/right side of the point given.
size?

**Comment by necropotame** [comment]
The text must be relative to the worlds, the same coordinate system than for entities.
An another NetObject, called NetObject_ModAPI_TextCharacter and containing a ClientID, do similar to NetObject_ModAPI_Text, but with coordinates relative to the character (pCharacter->m_Pos).

For alignment, we can add this enum:
enum
{
MODAPI_TEXTALIGN_CENTER = 0,
MODAPI_TEXTALIGN_RIGHT_BOTTOM,
MODAPI_TEXTALIGN_RIGHT_CENTER,
MODAPI_TEXTALIGN_RIGHT_TOP,
MODAPI_TEXTALIGN_CENTER_TOP,
MODAPI_TEXTALIGN_LEFT_TOP,
MODAPI_TEXTALIGN_LEFT_CENTER,
MODAPI_TEXTALIGN_LEFT_BOTTOM,
MODAPI_TEXTALIGN_CENTER_BOTTOM,
};
and add m_Align in NetObject_ModAPI_Text.

**Comment by killaTW** [comment]
Should this be a NetObject or a NetMessage?
The problem with NetObjects is that u cant pack a string in it (thats why the NetObject De_ClientInfo uses an int array and the methode StrToInts). If we will also use this way, we need to discuss the max length for a text (length/4 would then be the size of the int array).

**Comment by necropotame** [comment]
It's a NetObject, because the position must be predicted (it's very similar to Sprite, and we must also implement a Character version). For the siez, I don't know. The length could be 2xsizeof(playername). But for internationalization, we need to multiply this by two, so we can use NetArray(NetIntAny("m_aText"), 16). What do you think ?
We can also think about implementing a NetObject with variable size. But I don't know how right now :-p

**Comment by killaTW** [comment]
ya length seems ok.
"This NetObject display a text on the world like names (same size and font)."
In my version i added color and size variables for the text ... is this ok or should i remove this?

"We can also think about implementing a NetObject with variable size. But I don't know how right now :-p"
thought the same ... but i have also no idea  right now

**Comment by necropotame** [comment]
> In my version i added color and size variables for the text ... is this ok or should i remove this?

Some text parameters must go in the .mod file and we should add a m_StyleID in the NetObject (later). The question of which parameters must go in this Style definition, or directly in the NetObject is not always easy. If the parameter can take an infinite number of values in the game, it should go in the NetObject. If not, it should go in the Style. For the color, I can understand that someone want to gradually adjust it depending of some variable (more or less red for exemple). For the size, the number of value are generally limited : size of Nameplate, size of chat message or size of broadcast. So this one could go in the Style.
But you can keep it and we will decide later. We are flexible until ModAPI is released ^^

**Comment by killaTW** [comment]
where should i add the enum with the alignments?

**Comment by necropotame** [comment]
You can put it here: src/modapi/graphics.h
