### ISSUE TITLE
Force gametype change

### ISSUE THREAD

**Issue by Henningstone** [teeworlds-modapi/teeworlds#33]
According to teeworlds masterserver rules, it is not allowed to run a server which is modified in any way with a gametype reserved for vanilla. (So in 0.7 "DM", "TDM", "CTF", "SUR", "LMS" is _not_ allowed!)

To prevent that, we could do the following (just as an example):
- Whenever the server runs one of the vanilla gametypes, broadcast them as `<gametype> (ModAPI)`, so a ModAPI server running DM would broadcast `DM (ModAPI)` as it's gametype to the masters.

**Comment by necropotame** [comment]
Good idea :-)
