### ISSUE TITLE
Add Version to all Custom NETMSGs

### ISSUE THREAD

**Issue by abck** [teeworlds-modapi/teeworlds#38]
Add Version to all Custom NETMSGs

That way, the NETMSGs can be **_extended_** without any problem.
Example: NETMSG_DRAW_LINE

```
<ID><int version=1><int x1><int y1><int x2><int y2>
```

could be extended to

```
<ID><int version=2><int x1><int y1><int x2><int y2><int thickness>
```

If a client with V1 receives a V2 netmsg, no special code is needed, since the packet is only **_extended_**

If a client with V2 receives a V1 netmsg, it could default the extended values to something
sample pseudocode: (im NOT a c/++ dev!)

``` c++
bytes_received // being the received data from the server
NETMSG_DRAW_LINE lineinfo; //(this is now V2, since the client has the V2 netmsgs installed)
memcpy(&lineinfo, &bytes_received, min(sizeof(bytes_received),sizeof(lineinfo)) );
if(version < 2){
  lineinfo.thickness = 1; // default to 1
}
```

**Comment by H-M-H** [comment]
True adding versions is important to maintain compatibility, though I would not recommend adding them to every netmsg/obj maybe rather check client/server version on connect.

**Comment by necropotame** [comment]
I agree with H-M-H. In addition, I try to limitate the size of NetObjects by putting information in the .mod file.

**Comment by abck** [comment]
H-M-H, you are right, checking the version once would be enough.

But i would give every netmsg/obj a version, since this would increase compatibility a lot. I also would only extend the netmsgs so they get backwards compatible (older clients can still understand the newer netmsg-versions).

**Comment by necropotame** [comment]
I'm not sure if it's even working. I think that the size of NetObjects must be known in advance, in order to move to thé next NetObject of thé snapshot.

**Comment by H-M-H** [comment]
Yes, with the current system you can not change the size of NetObjects without notifying the client.

**Comment by abck** [comment]
what about NETMSGs? was actually not thinking about netobjects

**Comment by necropotame** [comment]
For NetMsg, it's okay, but we don't really need to change them. And it's super easy to send different version depending the client. It's how the compatibility with vanilla 0.7 is done.

**Comment by H-M-H** [comment]
As long as you add the extrainfo to the end of the netmessages everything should be fine.
