### ISSUE TITLE
Add MOTD as alternative for broadcasts

### ISSUE THREAD

**Issue by necropotame** [teeworlds-modapi/teeworlds#4]
Add a new alternative in CModAPI_Msg_Broadcast that send a "message of the day" to clients that don't support broadcasts.

**Comment by Henningstone** [comment]
Oh, don't know if that is optimal… Imagine a mod which always displays some message(s) via broadcast, and the player without broadcast support is totally annoyed because he can't get rid of the god forsaken motd-screen. At least I would be annoyed :/

**Comment by necropotame** [comment]
It optional. Broadcast are sent like this in ModAPI :

CModAPI_Msg_Broadcast MyBroadcastMsg(pGameServer, MODAPIALT_BROADCAST_MODT); MyBroadcastMsg.Send(ClientID, "My broadcast message");

If you change MODT by CHAT, a chat message is sent instead. If you change it by NONE, nothing is sent.

**Comment by Henningstone** [comment]
Ok now I see, so it's up to the mod maker to annoy players xD
