### ISSUE TITLE
Add EntityPoints

### ISSUE THREAD

**Issue by necropotame** [teeworlds-modapi/teeworlds#45]
The actual map format contains three important parts : the graphical part (client only), the entity part (server only) and the physical part (both).
The problem is that the physical part and the entity part are defined at the same place, the game layer. It's still okay for vanilla game types, but for mods, the map must contains a lot of informations that only the server needs. My proposition is to add two MapItems: ZoneLayer and EntityPoint. The Entity point is just a coordinate with an ID. This allows to place pickups of any kind and not necessary align with the grid. We can add extra params like angle, ammo, ... The vanilla client will not read this information, but he don't need it anyways. The format and the list of different type of EntityPoint must be defined, but it will add much more flexibility for modding and mapping.

**Comment by killaTW** [comment]
"the map must contains a lot of informations that only the server needs." 
But all that still in one file? That would mean that the clients download much more than they need (all the server stuff).

**Comment by necropotame** [comment]
There is two possibilities. The editor can export two files, or the server can send only a part of it. I like this one because the server can adapt the map to each client to avoid compatibility problems. In particular for the "physics" part.

**Comment by killaTW** [comment]
"or the server can send only a part of it." 
But then the server has to change much in the map structur (removing unused parts,changing offsets and so on)
Edit:
Nevermind ... we can save the serverinfos at the end of the map.

**Comment by necropotame** [comment]
Yes, but it should not be a problem. We can create a function called CreateClientMap() that read the map and save it in a different format. I think that the editor don't have to know how each client works. It's more the role of the server. But maybe it's better to let the editor do it.

Anyways, this is the second step. The first should be implementing this new MapItem and just put it in the .map.

Like usual, feel free to critic more this suggestion ;-)

**Comment by necropotame** [comment]
This issue is now only related to EntityPoints. A new issue must be created for ZoneLayers
