### ISSUE TITLE
Add mod examples

### ISSUE THREAD

**Issue by necropotame** [teeworlds-modapi/teeworlds#54]
We must provide an example mod made with ModAPI. The old target shooting must be recoded entirely to be sure that only the ./src/mod directory is edited. We can delete the old branch "server-example" and replace it by "mod-target" instead.

**Comment by Henningstone** [comment]
Would be nice if we could manage to also have an example for NetGUI in this new one. I would write a nicer example for this instead of taking the one of my repo.

**Comment by necropotame** [comment]
You can start by adding NetGUI into ModAPI first :-D

What about a simple leadboard that show the best score of the day ?

**Comment by Henningstone** [comment]
> You can start by adding NetGUI into ModAPI first :-D

Yeah, my above post implemented that :)
I have pretty much finished, and if you are happy with the current state (also renaming etc), it should be ready for a PR into master.

> What about a simple leadboard that show the best score of the day ?

That's an awesome idea! Though, how do you imagine this leader board? (Bear in mind that there are no Listboxes yet.. I already tried to implement them but I somehow failed, everything was bugged)

**Comment by necropotame** [comment]
We can start with a list of labels. You can add also a NetMsg_ModAPI_Sv_GuiTee that allows to render a Tee like in the leadboard and in kill messages ^^ But I'm not sure about the parameters. ClientID ? But It could be funny to also render Tees based on the SkinModifier. Then, you can show a class selector with an pre-visualisation of the class.
