### ISSUE TITLE
Add NetGUI in ModAPI

### ISSUE THREAD

**Issue by necropotame** [teeworlds-modapi/teeworlds#6]
Merge both project, rename NetGUI to ModAPI in the code, remove examples

**Comment by Henningstone** [comment]
Why rename it? Or, what exactly to rename? The variables, functions, etc??

**Comment by necropotame** [comment]
I'm thinking about class name and defines in network.py. For example:

CNetGui -> CModAPI_Gui (server)
CNetGui -> CModAPI_GuiClient or CModAPI_GuiComponent (client)
NETMSGTYPE_CL_NETGUI_TRIGGEREVENT -> NETMSGTYPE_MODAPI_CL_GUITRIGGEREVENT

But it's not the priority, we can change it later :)

**Comment by necropotame** [comment]
I've added you as collaborator. You can work in the "NetGUI" branch. When the branch is ready, I will merge it with the master branch.

**Comment by Henningstone** [comment]
Ok, thanks. But I'm really unsure if I want renaming… To be more precise, it's about license trouble. In my license it says "you are not allowed to distribute NetGUI as it were yours". But renaming everything would make it look like if you made it in the course and as a part of your mod, which basically _is_ distributing it as if it were yours.
But yes, let's discuss that later. First things first, it wants to be implemented at all so I'll start with that :D

**Comment by H-M-H** [comment]
@Henningstone I guess it is fine if the author (you) does the changes + you could add yourself to credits somewhere ^^

**Comment by necropotame** [comment]
The fact that you have implemented the GUI part of ModAPI is a public information. In addition, you are a part of the ModAPI devs, so you are implicitly linked to any part of its code.
I will add a Readme with the list of main contributors and a sentence somewhere like "The GUI part of this project is based on NetGUI by Henningstone".

**Comment by Henningstone** [comment]
Well, that'd be completely fine then ^^
I'll start with the implementation tomorrow, as I just found a strange bug introduced within my last couple of commits, which needs to be fixed first. I also had ideas about special features based on ModAPI ;) e.g. sprites, iconified buttons, etc etc...

**Comment by necropotame** [comment]
Nice. Please post an issue for any idea you want to implement. It's always better to discuss before implementing.

**Comment by Henningstone** [comment]
Well, I said I'll start tomorrow… The thing is: I just finished it :wink: 
Commit is on it's way... :package:

**Comment by Henningstone** [comment]
For renaming… How would you like the NetMsgs to be called?
e.g.
`CNetMsg_Cl_ModAPI_Gui_TriggerEvent` or `CNetMsg_Cl_ModAPI_GuiTriggerEvent`, or something else?

**Comment by necropotame** [comment]
Something like that:
NetMessage("Sv_NetGui_InfoBox", [
--->
NetMessage("ModAPI_Sv_GuiInfoBox", [

**Comment by Henningstone** [comment]
Don't you want the `Sv` to be in front of it to be consistent with teeworlds convention?
so rather `NetMessage("Sv_ModAPI_GuiInfoBox", [`

**Comment by necropotame** [comment]
Ok, but we must also change it for broadcast.

**Comment by Henningstone** [comment]
I did so yet, because you created an issue for it (#5) :smiley: 
See 67a72c006c031690ac7d27552949f8852f4ef7dc, e3663d6f6a4a7e98ab5226c570d2c3ba746e77a1

**Comment by necropotame** [comment]
I know, but you did ModAPI_Sv, not Sv_ModAPI (you did well for the issue, but not for the new convention that you ask ;-) )

**Comment by Henningstone** [comment]
Actually.... although I think it's good to stick to the existing convention, marking all ModAPI msgs as such would be more convenient. Well, it's up to you then, we can do both :P

**Comment by necropotame** [comment]
Maybe in some cases, the message will exists for both client and server and no Sv/Cl will be needed. For this case, having ModAPI in first would be better. So let's keep ModAPI_Sv ;-)

**Comment by necropotame** [comment]
I've changed the structure of ModAPI files. Now, there is a client/server/shared folder into src/modapi. engine/mod.h and engine/shared/mod.cpp moved to ./src/modapi/shared. The same must be done for NetGUI. Any new file must go in src/modapi.

**Comment by necropotame** [comment]
ModAPI will implement its own GUI system in the client to make possible more personalisation. There is no more needs for use the vanilla GUI system. This means that NetGUI will not be adapted to ModAPI but recoded instead, using its custom GUI system.
