### ISSUE TITLE
Add GUI flags

### ISSUE THREAD

**Issue by Henningstone** [teeworlds-modapi/teeworlds#61]
these flags determine when to show a specified GUI element:
- `MODAPI_GUIFLAG_MENU`: show them in the ESC menu only
- `MODAPI_GUIFLAG_HUD`: display it as part of the teeworlds HUD
- `MODAPI_GUIFLAG_INGAME`: unlock the mouse immediately when this arrives

I'm not sure about the implementation of the flag though. Adding a new parameter to every netmsg seems pretty much to me, maybe someone can imagine an easier way?

ref #60

**Comment by necropotame** [comment]
You can use the last 2 bits at the end of the m_ID.

**Comment by Henningstone** [comment]
Hmm that would be a pretty hacky solution... hacky in a somehow nice way this time ;)
Also it is very unlikely that anybody will use an ID that is big enough to fill the whole integer. Good solution :+1:

**Comment by necropotame** [comment]
After checking the code, the size will be bigger by doing this than adding a new integer in the structure. The size of integers is variable after compression, so an integer starting and ending with bits set to "1" will use 4 bytes, while two small integers will takes between 2 and 5 bytes depending of the maximum value of m_ID.
