### ISSUE TITLE
Add multi-snapshot system for the server

### ISSUE THREAD

**Issue by necropotame** [teeworlds-modapi/teeworlds#8]
The server must create two different snapshots, one for 0.7 and one for ModAPI clients.
Each entities must implement Snap07() and Snap07ModAPI().

**Comment by necropotame** [comment]
I've created the branch "multisnapshot" to implement it.

In the CServer class m_IDPool should be replaced by m_IDPool07 and m_IDPool07ModAPI.
In vanilla entities, by default, a SnapID is reserved in the constructor. With a multi snapshot system, this is no more possible. Two solutions are possible :
- Reserve two IDs, one for each snapshot type.
- Let each entity reserve the number of ID that it want.

I prefer the second choice, because for some entities, the 0.7 alternative will need more than one SnapID. The abstract entity could have an array of ID for each protocol and a protected function like ReserveSnapID_07(int nbID) and ReserveSnapID_07ModAPI(into nbID). Then each entity call this function in the constructor.

**Comment by ghost** [comment]
merged the pr into master, can we close it now?
