### ISSUE TITLE
Esc to exit assets editor

### ISSUE THREAD

**Issue by android272** [teeworlds-modapi/teeworlds#82]
In Teeworlds 0.7 when you are in Play, (but not the Map Editor), Demos, or Settings and you press the Esc key it returns you to the home screen.

I purpose that when in the Assets Editor pressing the Esc key would ask the user to save unsaved works and then return to the home screen once this is done.

**Comment by necropotame** [comment]
Esc will show the main menu. But nothing will be saved and the editor will stay in his curent state. Like for the map editor, a message will be displayed only if you quit the game (but this will need time to implement this)
