### ISSUE TITLE
Tool Hints in the Assets Editor

### ISSUE THREAD

**Issue by android272** [teeworlds-modapi/teeworlds#83]
Although vanilla Teeworlds does not have tool hints it would be nice to be able to mouse over tabs and buttons in the Assets Editor to find out what they are or do.

![crop_tool_accident_ssssssssssssss](https://cloud.githubusercontent.com/assets/5912527/14751015/d3ea30a4-0895-11e6-9085-1db5981747a6.gif)

**Comment by necropotame** [comment]
Must be implemented as in vanilla 0.7.

**Comment by necropotame** [comment]
It's done in the last commit, but only for tools (just question of time)

**Comment by necropotame** [comment]
Done for tabs
