### ISSUE TITLE
Make ModAPI servers compatible with 0.6 clients

### ISSUE THREAD

**Issue by necropotame** [teeworlds-modapi/teeworlds#9]
An abstract layer should be used for NetClient and NetServer, to allow connections using different protocol. This is needed if we want compatibility with 0.6.

**Comment by necropotame** [comment]
The tricky part is in network.cpp, line 203. We must detect if the client is 0.6 or 0.7 to read the token or not. But we don't have any information about the client at this step. Maybe we can try with token and if the packet is wrong, try again without.

**Comment by Henningstone** [comment]
But making token optional would make the server vulnerable for spoofing again... Also, a 0.6 client or a spoofed dummy would look like the same for the server.

**Comment by necropotame** [comment]
I don't really know how spoofing is used in TW, but the compatibility with 0.6 must be optional, anyway. I think compatibility with 0.6 is interesting because we can with it release ModAPI when we want. It's possible that 0.7 take sometimes before be released. Even when 0.7 will be released, the compatibility can help to avoid the period when one part of players are in 0.6 and one other in 0.7, leading to two boring server instead of one enjoyable full server.
And maybe the DDnet community will take times to switch to 0.7.

For the technical part, we can go with multi-port support. The server can be opened with two ports, one for 0.6 protocol and one for 0.7/ModAPI protocol. Then, we don't have to detect the type of packet and the server is visible in the server list for both TW versions.
